### PR TITLE
Mixins

### PR DESCRIPTION
**Pull request by kRITZCREEK**
As a first Draft.
No typesafety as of yet.
Doesn't provide a way to expose methods to the components context.

### CODE REVIEW

**Comment by paf31** [comment]
Looks good, but I wonder if it would be possible to find a way to avoid having to specify mixins every times.

The thing I like about `Spec` right now is that it only requires those things which you need in pretty much every application.

I was thinking of taking this approach to support the lifecycle events:

- Change `Spec` to a foreign type
- A basic `Spec` can be constructed from a `SpecRecord`.
- Add additional constructors ("modifiers"?) which add fields to the `Spec`.

What do you think? We could use a similar approach here.

We could also then move the mixins stuff into a `Thermite.Mixins` module.

One other nice thing about this is that we could reuse the functions to construct `Mixin`s.

**Comment by kRITZCREEK** [comment]
I recently found this blogpost about comonads where the author shows that comonads are suited to reproduce common OO patterns in Haskell.
http://www.haskellforall.com/2013/02/you-could-have-invented-comonads.html

From an object oriented viewpoint our requirements sound a lot like the builder pattern where you  usually specify sensible defaults (like say ``[]`` for ``mixins``) and only set the properties that you are interestend in.

Does this sound like a route worth exploring?

**Comment by paf31** [comment]
So the builder pattern is basically what we're doing with `componentMounted` right now. Maybe we can do that here, and I'll have a think on the `Comonad` idea.

**Comment by kRITZCREEK** [comment]
Do you mean the simpleSpec constructor? Sorry but a search for componentMounted on the repository only finds this PR.

**Comment by paf31** [comment]
Sorry I meant `componentWillMount`: 

https://github.com/paf31/purescript-thermite/blob/master/src/Thermite.purs#L43

**Pull request closed without merging**
