### PR TITLE
Use Coroutine/CoTransformer for PerformAction API

### PR DESCRIPTION
**Pull request by paf31**
@pkamenarsky I've reverted back to the `Producer (s -> s)` approach, for the reasons given in your PR. Could you please have a look at this, and let me know what you think?

If this looks okay, I'll make a 1.0 release.

Thanks!

### CODE REVIEW

**Comment by pkamenarsky** [comment]
Looks good, but not having an async `get` primitive is a fundamental problem in my opinion. Maybe it would be better to wait and think about the free monad approach a bit more before committing to `Producer` and then still maybe going back to free later.

**Comment by paf31** [comment]
Can you please describe a case where you need `get` and not just `modify`? Thanks.

**Comment by paf31** [comment]
@pkamenarsky Could you take a look at the latest version please? I think it is the best of both worlds:

- We get to keep using `coroutines`, so we have a standard language for talking about asynchronous stuff which can interoperate with producers and consumers
- We get to observe the new state after every `cotransform` (wrapped in a `Maybe` to handle failure).

Please let me know what you think. If this seems okay, I'll make a release.

**Comment by paf31** [comment]
@pkamenarsky Ping. Do you have time to go over this? I'd like to get a 1.0 release out soon if possible.

Thanks :)

**Comment by pkamenarsky** [comment]
Looks good! I think this is a good compromise for now, if we come up with a better abstraction we can still change it later on.

**Comment by paf31** [comment]
Thanks!

**Pull request merged**
