### PR TITLE
Fix #3

### LINKED ISSUE #3: Allow use of 3rd Party React Components
A lot of React's philosophy is about the reusability of components. Enabling use of given React components written in Javascript would allow also allow partially porting a codebase to purescript. See eg, [React Bootstrap](http://react-bootstrap.github.io/)

### PR DESCRIPTION
**Pull request by paf31**
@kRITZCREEK @joneshf How does this look?

This should enable users to reuse third party components by importing them using the FFI.

### CODE REVIEW

**Comment by splodingsocks** [comment]
Just dropping the question here. It looks like this was addressed in #4, but those code changes don't appear to be around anymore, and I haven't found out when / why they were removed, and in favor of what approach.

**Comment by paf31** [comment]
This library uses the types from `purescript-react` now, so it should be possible to do the same things with that library instead.

**Comment by splodingsocks** [comment]
K, great. Just for posterity, here's how sjanssen on Slack pointed out:

If I have come component Foo, in my native js file:

```
exports.fooClass = Foo
```

And PS side:

```
foreign import fooClass :: ReactClass props -- (where props can be a custom type that describes the props specific to that component)

foo :: forall props. props -> Array ReactElement -> ReactElement
foo = createElement fooClass

-- and if you want to be able to use foo like this: foo [] []` then:
foo' :: forall props. Array Props -> Array ReactElement -> ReactElement
foo' props children = createElement fooClass (unsafeFromPropsArray props) children
```

Where `ReactElement, ReactClass, createElement and unsafeFromPropsArray` are all from `purescript-react`

**Comment by splodingsocks** [comment]
thanks, @paf31 👍  😄  🍰

**Pull request closed without merging**
