### PR TITLE
Add renderTo function

### PR DESCRIPTION
**Pull request by passy**
In addition to `render` which renders into `document.body`, allow
rendering into an arbitrary DOM Node.

It's very likely that you thought about this before and decided against it. In that case, please don't feel bad about closing this. ;)

### CODE REVIEW

**Comment by paf31** [comment]
> It's very likely that you thought about this before and decided against it. 

Nope, just pure laziness on my part ;)

Can we share code between `render` and `renderTo`? Also, your docs look a bit incorrect. Are you generating them using `psc-docs`?

**Comment by passy** [comment]
> > It's very likely that you thought about this before and decided against it.
> Nope, just pure laziness on my part ;)

Phew!

> Can we share code between render and renderTo?

I'm not too familiar with the FFI mechanism yet; can I call to the native `renderToImpl` function from `renderImpl`? Or would you prefer having a declaration for `document.body`?

> Also, your docs look a bit incorrect. Are you generating them using psc-docs?

Woops, was actually hand "generating" them. Will have a look at psc-docs later.

**Comment by paf31** [comment]
> Can I call to the native renderToImpl function from renderImpl? Or would you prefer having a declaration for document.body?

The former is sometimes possible but gets in the way of dead code elimination. I'd recommend the second option.

For the docs, if you have `pulp`, you can probably just run `pulp docgen` or whatever the command is.

**Comment by passy** [comment]
Can you have a look at that change? I don't know if there's a nice point-free version to express this.

> For the docs, if you have pulp, you can probably just run pulp docgen or whatever the command is.

There's `pulp docs` but the format is vastly different. Is it possible that you generated those with an older version?

**Comment by paf31** [comment]
Yes, they can be updated to the new format.

**Comment by passy** [comment]
Alright, done. :)

**Comment by paf31** [comment]
Thanks!

**Pull request merged**
