### PR TITLE
Adding displayName to the Spec

### PR DESCRIPTION
**Pull request by ethul**
Allows the user to specify a display name for the component. This is set automatically by the JSX compiler when using JSX. When the display name is not set, all components are displayed as `<Unknown>`.

I realize this is adding an additional property to the Spec record. However, I admit that being able to name the components was quite helpful during app development and debugging. If your intention is to keep the Spec small, I could go either way on this. Or perhaps there is a better or alternative approach? I am open to ideas!

### CODE REVIEW

**Comment by paf31** [comment]
Looks good, but how do you actually specify the display name?

**Comment by paf31** [comment]
Also, could you please exclude `example/index.js`?

**Comment by ethul** [comment]
Ah, will do on the exclude for `example/index.js`.

I was thinking to manually create a spec to specify the display name. But I can add a function `displayName` similar to [componentWillMount](https://github.com/paf31/purescript-thermite/blob/master/src/Thermite.purs#L26-27). Would this be good?

**Comment by paf31** [comment]
I was thinking that something like `componentWillMount` would be nice. Otherwise, the user will have to use `SpecRecord` directly, right? Really, I'd like to move that type into an internal module.

**Comment by ethul** [comment]
Right. I've added the `displayName` function.

**Comment by paf31** [comment]
:+1: thanks!

**Comment by ethul** [comment]
Thank you!

**Pull request merged**
